model_provider = "anthropic"
embedding_provider = "voyageai"
reranker_provider = "voyageai"
max_concurrent_requests = 5
max_retries = 3

[anthropic]
model = "claude-sonnet-4-6"
api_key = ""
max_tokens = 64000

[ollama]
model = "zai-org/glm-4.7-flash"
model_small = "google/gemma-3-1b"
#model = "qwen/qwen3-vl-4b"
#model_small = "qwen3.5-0.8b-mlx"
max_tokens = 8192
embedding_model = "qwen3-embedding"
embedding_dims = 4096

[openai]
model = "gpt-5.4"
max_tokens = 128000
embedding_model = "text-embedding-3-large"
embedding_dims = 1536

[gemini]
model = "gemini-3.1-pro-preview"
embedding_model = "gemini-embedding-001"
embedding_dims = 3072

[voyageai]
reranker = "rerank-2.5"
embedding_model = "voyage-4-large"
embedding_dims = 2048
api_key = ""

[cohere]
reranker = "rerank-v3.5"
embedding_model = "embed-v4.0"
embedding_dims = 1536

[openrouter]
model = "anthropic/claude-sonnet-4.6"
