#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
email = "yrahul3910@gmail.com"
name = "Rahul Yedida"

[revsets]
bookmark-advance-to = 'closest_pushable(@)'

[signing]
behavior = "drop"
backend = "gpg"

[git]
sign-on-push = true

[aliases]
ba = {
    definition = ["bookmark", "advance"],
    doc = "Advance bookmark"
}
bl = {
    definition = ["bookmark", "list"],
    doc = "List bookmarks"
}
bt = {
    definition = [
        "util", "exec", "--", "bash", "-c", """
        set -eu
        jj bookmark create "$1"
        jj bookmark track "$1"
    """, ""],
    doc = "Create a bookmark and track its remote"
}
cm = {
    definition = ["commit", "-m"],
    doc = "commit :3"
}
f = {
    definition = ["git", "fetch", "--tracked"],
    doc = "Fetch tracked branches from git"
}
gfm = {
    definition = ["git", "fetch", "--branch", "main"],
    doc = "Fetch `main` from git"
}
l = {
    definition = ["log", "-r", "(main..@):: | (main..@)-"],
    doc = "Log pending changes"
}
p = {
    definition = [
        "util", "exec", "--", "bash", "-c", """
        set -eu
        jj bookmark advance || true
        jj git push "$@"
    """, ""],
    doc = "Advance bookmark and push to git"
}
pp = {
    definition = [
        "util", "exec", "--", "bash", "-c", """
        set -eu
        jj bookmark advance || true
        jj git push --dry-run "$@"
        jj undo
    """, ""],
    doc = "Preview what 'jj p' would advance and dry-run push"
}

[revset-aliases]
# Closest revision that is mutable, described and either non-empty or a merge
# See `jj help -k config`
'closest_pushable(to)' = '''
  heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))
'''
# Avoid accidentally overwriting others' commits/editing history
"immutable_heads()" = "builtin_immutable_heads() | (trunk().. & ~mine())"

[ui]
editor = "nvim --clean"

[templates]
commit_trailers = '''
format_signed_off_by_trailer(self)'''
